# Generated by Django 3.2.9 on 2021-11-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото пользователя')),
                ('username', models.CharField(max_length=30, verbose_name='Ф.И.О')),
                ('company', models.CharField(max_length=30, verbose_name='Название компании')),
                ('city', models.CharField(max_length=30, verbose_name='Город')),
                ('description', models.TextField(verbose_name='Описание')),
                ('star', models.IntegerField(verbose_name='Колличество звездочек')),
            ],
            options={
                'verbose_name': 'Один',
                'verbose_name_plural': 'Два',
            },
        ),
    ]
