# Generated by Django 3.2.9 on 2021-11-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'verbose_name': 'отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterField(
            model_name='meeting',
            name='photo',
            field=models.ImageField(upload_to='media', verbose_name='Фото пользователя'),
        ),
    ]
