# Generated by Django 3.2.9 on 2021-11-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexing', '0002_auto_20211116_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Фото мероприятия')),
                ('subclass', models.CharField(choices=[('Weddings', 'Свадьбы'), ('Corporate', 'Корпоративы'), ('Team', 'Тимбилдинги'), ('presentations', 'Презентации'), ('conference', 'Конференции'), ('child', 'Детские мероприятия'), ('concert', 'Концерты')], max_length=100, verbose_name='Какого типа мероприятие?')),
                ('title', models.CharField(max_length=20, verbose_name='Название мероприятия')),
                ('description', models.TextField(max_length=50, verbose_name='Краткое описание')),
            ],
        ),
        migrations.AlterField(
            model_name='meeting',
            name='description',
            field=models.TextField(max_length=340, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='photo',
            field=models.ImageField(upload_to='media/', verbose_name='Фото пользователя'),
        ),
    ]
