# Generated by Django 3.2.9 on 2021-11-16 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexing', '0003_auto_20211116_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'отчет с мероприятия', 'verbose_name_plural': 'Отчеты с мероприятий'},
        ),
    ]
