# Generated by Django 3.2.9 on 2021-11-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexing', '0004_alter_event_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=300, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название мероприятия'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='star',
            field=models.IntegerField(default=5, verbose_name='Колличество звездочек'),
        ),
    ]
